name               = "trio-media-upload"
main               = "media-upload.js"
compatibility_date = "2024-11-01"

[vars]
FIREBASE_PROJECT_ID = "nkm-ind"
CLOUDINARY_CLOUD_NAME = "vyhglthg"  
CLOUDINARY_API_KEY = "875538742951686"